name: maison-a-vendre-bromont
favicon: null
layout_spectrum: 0.35451
typography_spectrum: 0.43237463175319135
title: Vaste de choix de maisons à vendre à Bromont
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#475347'
    - '#101109'
    - '#77b189'
    - '#cf2520'
  brandStrength: 0.7764590939041227
  lightness: 0.6700428740587085
  saturation: 0.8308346399571747
  rhythmicContrast: 0.9736061589792371
purpose: []
